language: java
dist: trusty
sudo: false

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

script:
- sh -c 'cd grobid-ner && mvn clean install -Dmaven.test.skip=true'

#after_success:
#  - mvn clean cobertura:cobertura org.eluder.coveralls:coveralls-maven-plugin:report
